version: '2'
version: '2'
services:
  web:
    build: .
    depends_on:
      - db
    volumes:
      - .:/workshop-testing:cached
    ports:
      - 3000:3000
    volumes_from:
      - bundle_cache
    environment:
      - BUNDLE_PATH=/bundle_cache
      - DATABASE_HOST=db
      - DATABASE_USERNAME=postgres
  db:
    image: postgres:11-alpine
  bundle_cache:
    image: busybox
    volumes:
      - /bundle_cache
